# Welcome to Jekyll!
#

# Site settings
title: Hidden Ceilings
description: |
  The guy who invented the first wheel was an idiot. 
  The guy who invented the other three, he was a genius. 
  -Sid Caesar
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/hiddenceilings
  github: https://github.com/hiddenceilings
  linkedin-square: https://linkedin.com/in/hiddenceilings
  facebook-official: https://facebook.com/hiddenceilings
  google-plus-square: https://plus.google.com/u/0/+hiddenceilings
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
